### ISSUE TITLE
Add Website Link to About Section and Host the Website

### ISSUE THREAD

**Issue by SAUMYXA** [jain-rishabh-21/DoctorVerse#118]
### Description of the new feature.

The current "about" section of the project does not include a link to the website. As a contributor at GSSOC'23, I propose adding a website link to the "about" section and hosting the website to make it easily accessible to users.

### Describe briefly how you would implement this new feature.

```bash
I want to host it on render.
```

### Contributor terms

- [x] I agree to follow the Contributing Instructions

**Comment by jain-rishabh-21** [comment]
Hey @SAUMYXA ! Go Ahead!

**Comment by SAUMYXA** [comment]
Thankyou @jain-rishabh-21 !!

**Comment by jain-rishabh-21** [comment]
Hey @SAUMYXA! I want some more information on this! Can you ping me on linkedin or discord?
