### ISSUE TITLE
Database Creation using MongoDB

### ISSUE THREAD

**Issue by Bhushan-Thombre** [jain-rishabh-21/DoctorVerse#12]
I would like to create a development mock database for the project to store different collections like doctor's collection, user's collection, etc.
Will create the database using MongoDB.
Kindly assign this to me.

**Comment by naveen8801** [comment]
Hi @Bhushan-Thombre, go ahead 🚀 and happing learning ❤️

**Comment by SatabrataPaul-GitAc** [comment]
Can I start working on this issue ? 
I would like to create a schema for different hospitals and clinics and also the doctors that are tied up with those ?

Kindly assign it to me

**Comment by naveen8801** [comment]
Hey @Bhushan-Thombre any update on it ?
