### ISSUE TITLE
feat: improve UI of Sign Up page

### ISSUE THREAD

**Issue by rishuraj1** [jain-rishabh-21/DoctorVerse#127]
### Description of the new feature.

We might need to create a new sign up page as the the current login page should be served for login purpose and its better to have a seperate login and sign up pages.

The idea is to design and create a sign up page similar to the current login page and add better functionality and designs for better user experience.

Please assign me this task under GSSoC '23. Thank You!

### Describe briefly how you would implement this new feature.

```bash
Some steps to implement this enhancement-
1. creation of a new page signup .js
2. adding better css properties and icons
```

### Contributor terms

- [X] I agree to follow the Contributing Instructions

**Comment by jain-rishabh-21** [comment]
I think we have a similar issue on which @Deepanshu0703 has already worked!

**Comment by rishuraj1** [comment]
@jain-rishabh-21  Alright then, let me create a login page as well so that already registered user can login. #126
