### ISSUE TITLE
docs: README.md file enhancement

### ISSUE THREAD

**Issue by DivyanshiNarang** [jain-rishabh-21/DoctorVerse#130]
### Description of the documentation deficiency / workflow suggestion.

Official documentation links are not added to these buttons. We can add official documentation links of the respective technologies used so that it will be helpful for new contributors.

<img width="394" alt="image" src="https://github.com/jain-rishabh-21/DoctorVerse/assets/74779601/83c09aab-da8a-4d87-b6ea-8aa2f1da4f09">

### Contributor terms

- [X] I agree to follow the Contributing Instructions

**Comment by sipsdaoracle** [comment]
Hi, please assign this to me.
