### ISSUE TITLE
Logo Redesign to Enhance Doctorverse Branding

### ISSUE THREAD

**Issue by me-shweta** [jain-rishabh-21/DoctorVerse#145]
### Description of the new feature.

I am Shweta Meena. Under GSSOC'24, I'm interested in redesigning the logo of DoctorVerse to enhance its visual appeal and better represent its mission as a trusted healthcare marketplace. Please assign me this task!
<img width="245" alt="Capture" src="https://github.com/jain-rishabh-21/DoctorVerse/assets/119609866/4820116a-f0ba-4aa8-ac05-8a6f850ffdd6">

### Describe briefly how you would implement this new feature.

```bash
The current design is also very good, but I think it can be made even more attractive by adding some vibrant colors and making a few minor changes.
```

### Contributor terms

- [X] I agree to follow the Contributing Instructions

**Comment by me-shweta** [comment]
@jain-rishabh-21 I have created some designs for the logo. Here they are. Let me know which design suits you best and if there are any changes you would like to make. 

<img width="438" alt="logo1" src="https://github.com/jain-rishabh-21/DoctorVerse/assets/119609866/d6a7cdba-e352-4ed4-b448-305bbfbc5794">
<img width="447" alt="logo2" src="https://github.com/jain-rishabh-21/DoctorVerse/assets/119609866/bf17553b-5d40-456e-ac95-b1c60c7b78e8">
<img width="441" alt="logo3" src="https://github.com/jain-rishabh-21/DoctorVerse/assets/119609866/e92f9df3-db57-4e9a-bb65-8a6a21a3c4af">
<img width="451" alt="logo4" src="https://github.com/jain-rishabh-21/DoctorVerse/assets/119609866/3a457b0f-cfcb-42b7-a1ed-af874c9b4328">

**Comment by me-shweta** [comment]
Thank you for liking my design suggestion. 
I would like to proceed by forking the repository and implementing the changes. Could you please confirm if this is okay?

**Comment by jain-rishabh-21** [comment]
Yes sure! Go ahead!
