### ISSUE TITLE
User routes/schema 

### ISSUE THREAD

**Issue by ayush25102001** [jain-rishabh-21/DoctorVerse#17]
Can I create the schema for the userModel?
I will also set login/signUp endpoint for user and connect with the Database(MongoDB Atlas) where all entries will be visible.
Participant under Gssoc’22.

**Comment by ayush25102001** [comment]
Can I implement this @jain-rishabh-21

**Comment by naveen8801** [comment]
Hey @ayush25102001 , go for it , happy learning 💻

**Comment by naveen8801** [comment]
Hey @ayush25102001 , any updates on it ?

**Comment by ayush25102001** [comment]
Will create a PR till tomorrow
