### ISSUE TITLE
signup and login ui page

### ISSUE THREAD

**Issue by sejalrai23** [jain-rishabh-21/DoctorVerse#18]
i would like to build the signup and login ui page . please assign me this issue

**Comment by jain-rishabh-21** [comment]
Go Ahead @sejalrai23

**Comment by sejalrai23** [comment]
i will work on dev part no so good with figma

**Comment by sejalrai23** [comment]
can i get figma design or any other refernce to build the ui ?

**Comment by naveen8801** [comment]
Hi @sejalrai23 are you willing to work on it, we have some designs ready 😄

**Comment by Tushar98644** [comment]
i would take up the issue @naveen8801

**Comment by MihirCharan42** [comment]
Hi i would like to work on this issue as well, could you please assign this to me? I am GSSoC'2023 participant

**Comment by AgentRittik** [comment]
@sejalrai23  can you please assign this issue to me  under GSSOC 2023 . i can make a very good login page with amazing animations

**Comment by jain-rishabh-21** [comment]
Hey! Let's wait for the mentors to get assigned and then we can decide on this! Thanks
