### ISSUE TITLE
Design the home page UI of the website

### ISSUE THREAD

**Issue by mohammadshaad** [jain-rishabh-21/DoctorVerse#19]
I am a GSSoC'22 contributor and I want to design the home page UI of DoctorVerse website
Kindly assign me this issue

**Comment by naveen8801** [comment]
Hi @mohammadshaad, go for it & happy coding 😄

**Comment by mohammadshaad** [comment]
I will be doing the designing part not the coding 😅

**Comment by naveen8801** [comment]
hi @mohammadshaad any update on it ?

**Comment by mohammadshaad** [comment]
> hi @mohammadshaad any update on it ?

I will definitely make a PR tomorrow
Actually I was busy in college projects so forgot to make the PR although the design is ready
