### ISSUE TITLE
Folder Structure For Client

### ISSUE THREAD

**Issue by naveen8801** [jain-rishabh-21/DoctorVerse#20]
## Describe the bug/feature
New Folder Structure for Client (React App)

## Expected behavior
![image](https://user-images.githubusercontent.com/54985099/163547872-0ace2737-0034-49ee-a2e4-ea758a06ebe1.png)

There should following changes:
* Change title to 'DoctorVerse'
* Add 'src' dir
* Add three different folders inside src as shown in above img
* Add 3 files inside pages folder - Home, Contact, About Us (for now)
* Add routing for the above pages using [React Router]('https://reactrouter.com/'), all the routes should be added to routes.js (inside src dir) and then 'useRouter' hook (from react-router-dom) should be called in App.js.

**Comment by Kanika637** [comment]
I would like to work on this issue under GSoC 2022.

**Comment by naveen8801** [comment]
Hi @Kanika637, sure go for it & happy coding :)

**Comment by Kanika637** [comment]
I have made the PR, kindly review it @naveen8801.

**Comment by naveen8801** [comment]
> I have made the PR, kindly review it @naveen8801.

@Kanika637 I have suggested some changes, check you PR
