### ISSUE TITLE
Designing UI mockups for the web end.

### ISSUE THREAD

**Issue by dasgupta002** [jain-rishabh-21/DoctorVerse#22]
## Describe the feature

As the frontend part is at scratch, I want to design UI mockups to be implemented at a later stage for faster coding.

## To Reproduce

Use Adobe XD for the web wireframe. I have previous experience in designing background and I am currently passionate hands on UI/UX stuff. 

## Expected behavior

If time permits I myself could start with developing the frontend myself.

## Additional Context

Myself being a GSSOC '22 contributor, I want to myself work on it.

**Comment by dasgupta002** [comment]
As @mohammadshaad is designing the home page, I can start with signup, login and landing page design and later add more on the run as per need!

**Comment by naveen8801** [comment]
@dasgupta002 sure, go ahead 👍
