### ISSUE TITLE
UI : Home Page

### ISSUE THREAD

**Issue by akankshat05** [jain-rishabh-21/DoctorVerse#26]
## Describe the bug/feature
#19 #24 
I  will write entire code for the frontend (homepage) using the above designs.
(Under gssoc22)

**Comment by naveen8801** [comment]
hi @akankshat05 go ahead and please keep the frontend responsive:
* Home -  https://www.figma.com/file/C9s7Lm4ALV7XZIxlpW9e0P/DoctorVerse?node-id=0%3A1

Happy coding 👍

**Comment by akankshat05** [comment]
sure! @naveen8801

**Comment by akankshat05** [comment]
@naveen8801 I will make a PR in a few days

**Comment by naveen8801** [comment]
> @naveen8801 I will make a PR in a few days

okay

**Comment by naveen8801** [comment]
@akankshat05 any updates ?

**Comment by akankshat05** [comment]
I'm working on it @naveen8801

**Comment by navyasharma0203** [comment]
@naveen8801 Can I work on this issue??

**Comment by MihirCharan42** [comment]
Hi i would like to work on this issue as well, could you please assign this to me? I am GSSoC'2023 participant

**Comment by jain-rishabh-21** [comment]
Hey! Let's wait for the mentors to get assigned and then we can decide on this! Thanks
