### ISSUE TITLE
techstack

### ISSUE THREAD

**Issue by Anurag-Raut** [jain-rishabh-21/DoctorVerse#34]
@jain-rishabh-21 
I assume we have to develop the project from the start.
Could you please open issues for frontend if you have some designs so front end folks can start building it.

Also forthe blockchain part what tech stack would you prefer to be used.
I had developed a similar type of application, where I used thirdweb and web3.storage (for ipfs).
we can also use other libraries like web3.js or moralis.

**Comment by jain-rishabh-21** [comment]
Hey Anurag! Yes we need to start this project from the start! 
Lets wait till we get the mentors in, and then we can decide! Thanks

**Comment by SaxenaAnushka102** [comment]
Hi @jain-rishabh-21!! I saw this project's stack has AWS in it. I'm a Cloud Computing enthusiast and would love to get involved in the modules of project that are related to AWS. Please let me know how can I get to know more regarding this.
Thanks,
Anushka Saxena.
