### ISSUE TITLE
Is there a group for this ? and what is the plan?

### ISSUE THREAD

**Issue by shivam-jainn** [jain-rishabh-21/DoctorVerse#37]
We need a discord server or channel itself to plan this out . From what i can see , the dependencies are deprecated and needs to updated . What are the future plans?

**Comment by jain-rishabh-21** [comment]
You can find it in the GSSOC23 discord server!

**Comment by jain-rishabh-21** [comment]
https://www.linkedin.com/in/rishabhjain21/
