### ISSUE TITLE
UI prototype!

### ISSUE THREAD

**Issue by jain-rishabh-21** [jain-rishabh-21/DoctorVerse#39]
If someone is interested in developing the full UI on FIGMA!

Things that are needed:
1. Homepage - Ideal landing page
2. Error 404 page
3. Login Portal
4. Dashboard for patients to see their vitals and reports
5. Dashboard for doctors to see their patients information and current schedule
6. A page to book the appointments for the concerned speciality
7. Doctors information page!

So, designing the UI can be a fairly large task!

If one person is willing to work on this!

I can open separate issues for separate pages! So, just let me know, how you want to work on this!

**Comment by yashraj-exe** [comment]
i have one osm Login and signup page for this project  mostly in this project i focus on backend but if you like this login and signup i can implement on in this project : 

https://github.com/jain-rishabh-21/DoctorVerse/assets/91207380/d465c470-b225-46c4-b07a-0db98d725530

**Comment by jain-rishabh-21** [comment]
Hey Yashraj! You have any experience using figma?

**Comment by Yashrajsinh-Solanki** [comment]
Heyy I would like to take this UI prototype thing under my GSSOC'23 as I'm contributor.
I can make the figma of your website. I can work on all pages also and if you want me to design all the pages then i can do that thing also.
but i will suggest that all the pages are made by one person so that there is no difference between different pages.

**Comment by jain-rishabh-21** [comment]
@Yashrajsinh-Solanki 
That would be great! If you are willing to work! Can you ping me on discord, I will have a connect with you once!

**Comment by ADITI-2003** [comment]
Hi, @jain-rishabh-21 sir, 
Being a web designer and a contributor in GSSoC'23, I would like to work on this issue and would build all the pages on Figma with consistent designs throughout the website. It's a time taking task and I can do it by giving my time as I am experienced in figma. Please assign me this issue and I will provide the Figma wireframe as soon as possible.
Thank you

**Comment by jain-rishabh-21** [comment]
Hey @ADITI-2003 , its great to hear that!
Can have a connect with you, can you ping me on discord / linkedin! Since its a big task! Do you mind working with @Yashrajsinh-Solanki on this?

**Comment by ADITI-2003** [comment]
> Hey @ADITI-2003 , its great to hear that!
> Can have a connect with you, can you ping me on discord / linkedin! Since its a big task! Do you mind working with @Yashrajsinh-Solanki on this?
> 

Sure sir I am in for working with @Yashrajsinh-Solanki .
I will ping you on discord right away sir.
Thank you

**Comment by Yashrajsinh-Solanki** [comment]
Heyy, @jain-rishabh-21 I have sent you connection request on linked in and Discord also.
just go check it.

@ADITI-2003 can we get connected on linked in so that we can have discussion about figma.

**Comment by Yashrajsinh-Solanki** [comment]
sure, @yashraj-exe here is my Linkedin ID https://www.linkedin.com/in/yashrajsinh-solanki-a92670243/

**Comment by vikashjalandra** [comment]
hey, when you get the Figma design of the website, please assign some of the pages to me, I will convert them to react code.
