### ISSUE TITLE
I would like to contribute in UI of the website using Figma

### ISSUE THREAD

**Issue by dexterousb** [jain-rishabh-21/DoctorVerse#4]
I am a Ui/Ux designer , designed various high fidelity prototypes , wireframes etc. 
I would like to contribute in this field of interest , Looking forward to hear from you soon !

**Comment by jain-rishabh-21** [comment]
Hey @dexterousb ! Go ahead and start working on figma prototypes for the landing page, 404 page and some other pages I will tell!
Don't worry about the issues! I will open separate issues with levels depending on their complexity and will assign you those!

**Comment by BeginnerCoder21** [comment]
I would also like to contribute my UI designing skills @jain-rishabh-21, can I also work on it?

**Comment by dexterousb** [comment]
Great I will start working on it ! @jain-rishabh-21

**Comment by jain-rishabh-21** [comment]
@dexterousb What is the status?

**Comment by jain-rishabh-21** [comment]
> I would also like to contribute my UI designing skills @jain-rishabh-21, can I also work on it?

@dexterousb is already working on it man! You can work together on it! We can connect offline and I can open separate issues and you both can divide then according to your convenience.

**Comment by jain-rishabh-21** [comment]
Can you update the status! After that only we can get started with the major development?

**Comment by naveen8801** [comment]
Hi @BeginnerCoder21 @dexterousb any updates?

**Comment by BeginnerCoder21** [comment]
Hello, @naveen8801! I'm not working on this issue because I've been contributing to other GSSOC issues, and dexterousb hasn't responded, so I'm not working on it right now.

**Comment by dexterousb** [comment]
hi @jain-rishabh-21 @naveen8801 I was not able to the assigned work , bcoz of sudden emergency!

**Comment by dexterousb** [comment]
@jain-rishabh-21 please assign @naveen8801 @BeginnerCoder21 the task , sorry for inconvenience!
