### ISSUE TITLE
add contributor graph

### ISSUE THREAD

**Issue by S-ishita** [jain-rishabh-21/DoctorVerse#40]
## Describe the bug/feature
I want to add contributor graph in readme
## To Reproduce
- Steps to reproduce the behavior:
1.Changes in readme file

## Expected behavior
Contributors shown in readme file

## Environment (please complete the following information):
- OS: any
- Browser:any

## Additional Context
Please assign this issue to me

**Comment by jain-rishabh-21** [comment]
Go ahead!
