### ISSUE TITLE
Making a logo for DoctorVerse

### ISSUE THREAD

**Issue by jain-rishabh-21** [jain-rishabh-21/DoctorVerse#46]
## Describe the bug/feature
- Create a new Logo for this

**Comment by AKsHaT123456A** [comment]
Hi @jain-rishabh-21 kindly assign me this issue

**Comment by jain-rishabh-21** [comment]
Hey @AKsHaT123456A whats the update?

**Comment by AKsHaT123456A** [comment]
Working on it @jain-rishabh-21

**Comment by jain-rishabh-21** [comment]
Hey man! Its been 5 days! Whats the ETA for this?

**Comment by AKsHaT123456A** [comment]
Hey @jain-rishabh-21 !I am really sorry i laptop was not with me, so i couldn't work ,also if you want any specific element in the logo please tell as it is my first time making for an organisation .

**Comment by jain-rishabh-21** [comment]
You can look at some AI-generated logos, and they come up with your own version on whichever app you are comfortable with! 
Read the project description and get a feel, for how the logo should be for this project! Need not to be fancy! 
Try to keep the colour scheme near blue/light purple.
You can use Canva / Adobe Illustrator / Photoshop, whichever is comfortable for you!

**Comment by AKsHaT123456A** [comment]
Okay thank you ! will give you updates till 31st or before

**Comment by jain-rishabh-21** [comment]
Hey Man! This looks good! Can you use these colors:
#424088 and #9694E4 and Red
Also, attach the PS, Canva Or AI file, whichever you used to create this!

**Comment by AKsHaT123456A** [comment]
Sure!okay i will attach it with the changes you asked

**Comment by AKsHaT123456A** [comment]
@jain-rishabh-21 here's the canvas file :-https://www.canva.com/design/DAFke0CJBYQ/fv0G6RyWAmhfsqZztXQJYg/edit?utm_content=DAFke0CJBYQ&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by jain-rishabh-21** [comment]
Great man! Just export it as pngin high res format and add a new folder named "Design" -> New Folder "Logo".
Add your pngs over there. And a text file with the canva link! And Raise a PR for it! 
Take help from @apeksha235, if you are unable to raise a PR

**Comment by AKsHaT123456A** [comment]
HI! @apeksha235,kindly help me as i am unable to raise a PR

**Comment by AKsHaT123456A** [comment]
Hi @jain-rishabh-21 @apeksha235 do i have to create a new branch for PR?

**Comment by apeksha235** [comment]
@AKsHaT123456A yes it's always a great practice to create a new branch and make your changes there, if you need help with it, let me know!

**Comment by AKsHaT123456A** [comment]
@apeksha235 should i name the branch with the task i got?

**Comment by apeksha235** [comment]
@AKsHaT123456A you can keep it as your name as well, anything you wish

**Comment by AKsHaT123456A** [comment]
@apeksha235 i have raised a PR , kindly check

**Comment by jain-rishabh-21** [comment]
Great Work Man thanks!
