### ISSUE TITLE
Front-End Development of Home Page

### ISSUE THREAD

**Issue by sam301100** [jain-rishabh-21/DoctorVerse#5]
I want to contribute in developing the front-end of this project. I request you to assign me this task, as I've started working on the home page already.

-GsSOC Contributor

**Comment by jain-rishabh-21** [comment]
Hey, So you can share the figma or Adobe XD mockup that you have planned! Already, @dexterousb is working on it! You can work together on some pages then you can start with the development part, once the UI is confirmed!
I will make multiple issues for fidderent pages, so don't worry about your score

**Comment by naveen8801** [comment]
@jain-rishabh-21 closing this
