### ISSUE TITLE
Build a jenkins pipeline 

### ISSUE THREAD

**Issue by apeksha235** [jain-rishabh-21/DoctorVerse#50]
## Describe the bug/feature
- Set up a Jenkins pipeline to automate our project's build, test, and deployment processes. 
- Tasks include installing Jenkins, configuring plugins, creating a pipeline script, defining stages, enabling continuous integration.

**Comment by MahendraDani** [comment]
@apeksha235 I would like to work on this issue!
Thanks!

**Comment by Dev79844** [comment]
Hey @apeksha235 ! I would like to work on this issue. Can you assign it to me under GSSOC'23

**Comment by MahendraDani** [comment]
@apeksha235 Is there any discord server for our project? Would you please send me the link?
Thanks!

**Comment by apeksha235** [comment]
- @MahendraDani I have assigned the issue to you, if you are not able to do it in 4-5 days, it will go to @Dev79844. 
- @Dev79844 you can work on other issues till then, I will come up with more issues soon.

**Comment by MahendraDani** [comment]
@apeksha235 
I am trying to set up the project locally by following the guidelines given in `ProjectSetup.md`.
After running the command `npm run dev` to start both the client-side and server-side I am facing this error:
![error](https://github.com/jain-rishabh-21/DoctorVerse/assets/116940083/61b2eef0-8dcf-4c9c-b80f-dcc88a87adf9)

While the projects client-side is looking like this on the browser:
![web](https://github.com/jain-rishabh-21/DoctorVerse/assets/116940083/fb1046ce-c869-4509-9812-4b70a6a7e583)

Please help me fix this error and run the project locally.
Thanks!

**Comment by MahendraDani** [comment]
@apeksha235 
My discord username is - Mahendra#1630
I will add the mongodb server on my pc, if there are any issues I will let you know.
Thanks for the help!

**Comment by apeksha235** [comment]
@MahendraDani I have sent you the invite link on discord.

**Comment by MahendraDani** [comment]
@apeksha235 I am still not able to solve the MongoDB error. Please guide me!
Thanks!

**Comment by Manogna-chinta** [comment]
well, I would like to contribute on this issue, since @MahendraDani @Dev79844 are in the queue , please assign the issue if they're not able to complete in given time. meanwhile i'll take my time to work on this issue

**Comment by jain-rishabh-21** [comment]
try reinstalling all the dependencies, and check if your mongo port. Just tell me if that doesn't work! WIll try to fix then issue

**Comment by MahendraDani** [comment]
@jain-rishabh-21 I would try reinstalling all the dependency and revert back to you.
Thanks!

**Comment by MahendraDani** [comment]
@jain-rishabh-21 @apeksha235 I have tried everything I could to fix the error that I am getting but it's still there.
What should I do now?

**Comment by MahendraDani** [comment]
@apeksha235  Mam is 10pm fine for you?

**Comment by MahendraDani** [comment]
@apeksha235 I am sorry for the delay.
I am setting up an entire CI/CD pipeline starting from opening issue to merging PRs.
I will complete this in a day or two.

Thanks!

**Comment by apeksha235** [comment]
No problem @MahendraDani

**Comment by MahendraDani** [comment]
@apeksha235 Thanks for your support!
I will raise a PR soon with all the changes. And I am building the pipeline using Github actions.
I will add the documentation for all the changes plus I have made a separate repo on my Github profile to test functionalities of all the components of the pipeline.
This is the reason for the delay!

Thanks!
