### ISSUE TITLE
[GSSoC’23] Categorize Doctors based on Diagnosis

### ISSUE THREAD

**Issue by roberanegussie** [jain-rishabh-21/DoctorVerse#52]
## Describe the bug/feature
Request for new feature.
Categorize doctors based on diagnosis into different groups to allow patients to easily access doctor's related to their diagnosis. 

## To Reproduce
- Steps to reproduce the behavior:
1. Create a sidebar with a list of diagnosis
2. Doctor's who specialized in that diagnosis can be categorized and found when clicking a diagnosis
3. The hospital the doctor works at and his/her working hours will be available.
4. A patient will then be able to find doctor's related to his/her diagnosis easily based on the nearby hospital and the time convenient to them. 

## Environment (please complete the following information):
- OS: Windows 10
- Browser: Chrome

 @jain-rishabh-21 if you see this issue as good feature to the project I'd like to work on it.

**Comment by roberanegussie** [comment]
> Hey @roberanegussie, I don't think doctors searching for patients is required. It's normally patients who search for the doctors. So you can try the other way round where patients are able to filter out doctors according to their need. What's your say? @jain-rishabh-21

That's a better idea to allow patients to find a doctor related to their need. The feature can have a doctor's address(address of the hospital he/she works at), the working hours of the doctor.

**Comment by apeksha235** [comment]
@roberanegussie could you edit the issue so I can review it?

**Comment by roberanegussie** [comment]
> @roberanegussie could you edit the issue so I can review it?

@apeksha235 I have edited the issue kindly review.

**Comment by apeksha235** [comment]
- perfect! @roberanegussie, will you be designing the page first? other contributors are working together on the designs on discord, so you can get in touch with them. 
- I have assigned the issue to you

**Comment by roberanegussie** [comment]
> * perfect! @roberanegussie, will you be designing the page first? other contributors are working together on the designs on discord, so you can get in touch with them.
> * I have assigned the issue to you

@apeksha235 Thank you. I will design the page first and ask for your review before going ahead with the code.

**Comment by apeksha235** [comment]
@roberanegussie  okay works!

**Comment by Priyank-Vaidya** [comment]
Hey, @apeksha235 I would like to work on building the Backend part of this feature. I'm a GSSOC Contributor and have experience in building backend applications.

**Comment by roberanegussie** [comment]
Hello @apeksha235, I started working on the UI and thought that I'd use the nav-bar design that was merged in issue #27. 
Will the website UI continue to use that nav-bar design ? I wanted to make sure before getting started with the code.

**Comment by Priyank-Vaidya** [comment]
Hey, @apeksha235 Is this Issue meant for the Design of the Page or also for development purposes as well? If yes I would like to work on developing the backend for this issue.
Thank you.

**Comment by roberanegussie** [comment]
> Hey, @apeksha235 Is this Issue meant for the Design of the Page or also for development purposes as well? If yes I would like to work on developing the backend for this issue. Thank you.

I will be designing the UI for the issue I raised and work on the frontend. If you get assigned the backend you can work on it after that.

**Comment by apeksha235** [comment]
@roberanegussie , I have sent you a request on discord, also could you assign the `doctorverse` role to yourself so you can get added to the channel as well.

**Comment by roberanegussie** [comment]
Hello @apeksha235, I am currently facing a problem trying to join the discord channel. However, until I resolve that issue I wanted to get your feedback on the prototype design I worked on using the figma.
https://www.figma.com/proto/7pPfkZox4RH8kFP0w2hJig/Untitled?type=design&node-id=101-2&scaling=scale-down&page-id=0%3A1&starting-point-node-id=101%3A2
