### ISSUE TITLE
Adding more information in doctor.js

### ISSUE THREAD

**Issue by Naman1729** [jain-rishabh-21/DoctorVerse#55]
## Describe the bug/feature
- There are some information which is important to know for patient about the doctor.

## Parameter added:
-1. Language : Preferred language for effective patient-doctor communication.
-2. Quality Assurance : Involvement in patient safety programs to demonstrate doctor commitment to providing high-quality care.
-3. Email Address: To connect the Doctor and Patient.

I want to work on this under GSSOC'23

**Comment by apeksha235** [comment]
Hey @Naman1729, I have assigned the issue to you
- you can also add more information like time availability etc.

**Comment by Hareesh108** [comment]
It is fixed? if not can i work on it? @apeksha235
