### ISSUE TITLE
Proper structuring of server side

### ISSUE THREAD

**Issue by SnehaJaiswal123** [jain-rishabh-21/DoctorVerse#62]
## All the folders and files on server side is unstructured
- Will make correct folder and structure it.

## To Reproduce
- Steps to reproduce the behavior:
1.Separate folders for sources
2.Separate route, controller, and model folder in source folder
3.All the files and folders have proper naming convention
4.Will maintain all the functioning of routes
## Expected behavior
- A clear and concise structure that will be easy to debug and error handling

## Environment (please complete the following information):
- OS: Window
- Browser: Chrome

## Additional Context
- Unstructured folder looks messy and ceases the motivation to work on project.

**Comment by SnehaJaiswal123** [comment]
@jain-rishabh-21 @Gurdeep475 ,Please review the issue and assign me.

**Comment by Hareesh108** [comment]
Can I work on this issue?

**Comment by apeksha235** [comment]
hey @SnehaJaiswal123 you can go ahead with it
