### ISSUE TITLE
Documentation : Create Issue Template

### ISSUE THREAD

**Issue by naveen8801** [jain-rishabh-21/DoctorVerse#7]
### Description:

* Create issue template it should be stored in `.github` dir.
* It should contain informations shown below:

![image](https://user-images.githubusercontent.com/54985099/156776311-59a594b9-f545-4f45-8765-e515f0aa8786.png)

**Comment by Gurdeep475** [comment]
I would like to work on this issue under GSSOC`22.

**Comment by naveen8801** [comment]
Hi @Gurdeep475, go ahead and happy learning 🚀

**Comment by Gurdeep475** [comment]
@naveen8801 I have made the PR, but someone for whom the issue was not assigned has also made the PR for the same issue, please check.

**Comment by naveen8801** [comment]
> @naveen8801 I have made the PR, but someone for whom the issue was not assigned has also made the PR for the same issue, please check.

Sure @Gurdeep475
