### ISSUE TITLE
Doctor's REST API and authentication

### ISSUE THREAD

**Issue by Deepanshu0703** [jain-rishabh-21/DoctorVerse#70]
### Description of the new feature.

I want to add some vital and necessary REST API for Doctor like create update and all i have already implemented token so i will connect both of them so that the user that have only admin rights can do that crud operations.

### Describe briefly how you would implement this new feature.

```bash
Some steps to implement this enhancement-
1. Step 1
creating the basic crud API
2. Step 2
implementing and checking the API
3. Step 3
securing it by connecting to jwt verification
```

### Contributor terms

- [X] I agree to follow the Contributing Instructions

**Comment by apeksha235** [comment]
@Deepanshu0703, i have assigned it to you, you can go ahead!
