### ISSUE TITLE
UI : Create Mockup For 404 Page

### ISSUE THREAD

**Issue by naveen8801** [jain-rishabh-21/DoctorVerse#8]
### Description

* Use figma and create mockup for 404 page

**Comment by Gurdeep475** [comment]
I would like to work on this issue under GSSOC`22

**Comment by naveen8801** [comment]
Hey @Gurdeep475, go ahead 🚀 , happy learning ❤️

**Comment by Gurdeep475** [comment]
I have made the Mock-Up for the 404 Error Page. https://www.figma.com/file/MCbVrfH1golRrRcs4cQfWZ/404-Error-Page-MockUp?node-id=0%3A1.

**Comment by jain-rishabh-21** [comment]
Can we shift from monochrome to a bit good color scheme?

**Comment by Gurdeep475** [comment]
changed from monochrome to red-yellow gradient theme https://www.figma.com/file/MCbVrfH1golRrRcs4cQfWZ/404-Error-Page-MockUp?node-id=0%3A1.

**Comment by Gurdeep475** [comment]
> changed from monochrome to red-yellow gradient theme https://www.figma.com/file/MCbVrfH1golRrRcs4cQfWZ/404-Error-Page-MockUp?node-id=0%3A1.

@jain-rishabh-21 review requested

**Comment by naveen8801** [comment]
@jain-rishabh-21 Looking good to me 👍

**Comment by naveen8801** [comment]
Hi @Gurdeep475 can you please do the following changes, will merge this PR after these changes:
* use color scheme same as in this file https://www.figma.com/file/C9s7Lm4ALV7XZIxlpW9e0P/DoctorVerse?node-id=0%3A1
* add png version of your image in mockup directory in root folder.
