### ISSUE TITLE
docs: Changing font in Image in Readme file

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [jain-rishabh-21/DoctorVerse#92]
### Description of the documentation deficiency / workflow suggestion.

I will be changing the font in the readme file image so that the full text is visible in the image

**Remotely** is not fully visible in the last part of the image

## Screenshot

![image](https://github.com/jain-rishabh-21/DoctorVerse/assets/85278243/7898e0ac-d001-4b45-849e-2e3d1c445ec8)
![image](https://github.com/jain-rishabh-21/DoctorVerse/assets/85278243/7a5fb3df-fdd2-46b2-a743-b9798d9e4bbb)

Please assign me this issue under GSSOC'23

### Contributor terms

- [X] I agree to follow the Contributing Instructions

**Comment by apeksha235** [comment]
go ahead @Swapnil-Singh-99

**Comment by Swapnil-Singh-99** [comment]
👍
